### ISSUE TITLE
Wrong hexadecimal digest and potentially incorrect test vectors

### ISSUE THREAD

**Issue by ghost** [iotaledger/kerl#3]
According to [this](https://github.com/iotaledger/kerl/blob/master/IOTA-Kerl-spec.md) page, the hexadecimal digest from the SHA3-384 hash function for string `Message` is `0c8d6ff6e6a1cf18a0d55b20f0bca160d0d1c914a5e842f3707a25eeb20a279f6b4e83eda8e43a67697832c7f69f53ca`, and the used Keccak implementation is claimed to be [`pysha3`](https://pypi.python.org/pypi/pysha3) for Python, except the expected result on said page is incorrect.

Python:
```
>>> import sha3
>>> import hashlib
>>> s = hashlib.sha3_384()
>>> s.name
'sha3_384'
>>> s.digest_size
48
>>> s.update(b"Message")
>>> s.hexdigest()
'cfc55cb4b6f445aca0641b0ed200bbdedef9351f80ee5090d8d1a90f45cf2696786caa2d4fafab455b15678bc517f0d4'
```

OCaml:
```
# #require "cryptokit";;
# let sha3 = Cryptokit.Hash.sha3 384;;
val sha3 : Cryptokit.hash = <obj>
# sha3#add_string "Message";;
- : unit = ()
# Cryptokit.transform_string (Cryptokit.Hexa.encode ()) sha3#result;;
- : string =
"cfc55cb4b6f445aca0641b0ed200bbdedef9351f80ee5090d8d1a90f45cf2696786caa2d4fafab455b15678bc517f0d4"
```

rhash:
```
$ printf "Message" | rhash --sha3-384 -
cfc55cb4b6f445aca0641b0ed200bbdedef9351f80ee5090d8d1a90f45cf2696786caa2d4fafab455b15678bc517f0d4  (stdin)
```

**Comment by alon-e** [comment]
The function used in `Kerl` is `keccak_384()`, not SHA3-384.  [L18](https://github.com/iotaledger/kerl/blob/master/python2/pykerl.py#L18)
SHA3 is a subset of the Keccak family selected by NIST.

a bit of background:
http://keccak.noekeon.org/yes_this_is_keccak.html
https://www.schneier.com/blog/archives/2013/10/will_keccak_sha-3.html

**Comment by ghost** [comment]
You are right. I was in the thought that SHA-3 is supposed to be Keccak, and failed to examine the code of `Cryptokit` more carefully.

Seems like it will be an easy switch:

```
# #require "cryptokit";;
# let keccak = Cryptokit.Hash.keccak 384;;
val keccak : Cryptokit.hash = <obj>
# keccak#add_string "Message";;
- : unit = ()
# Cryptokit.transform_string (Cryptokit.Hexa.encode ()) keccak#result;;
- : string =
"0c8d6ff6e6a1cf18a0d55b20f0bca160d0d1c914a5e842f3707a25eeb20a279f6b4e83eda8e43a67697832c7f69f53ca"
```

Feel free to close this non-issue.

**Comment by tawago** [comment]
Just for future reference. Pysha3
```
>>> import sha3
>>> k = sha3.keccak_384()
>>> k.update(b"Message")
>>> k.hexdigest()
'0c8d6ff6e6a1cf18a0d55b20f0bca160d0d1c914a5e842f3707a25eeb20a279f6b4e83eda8e43a67697832c7f69f53ca'
```
